#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# Copyright (C) 2022 Modified by:
# 	Recluse389 (Jay B) <57876007+Recluse389@users.noreply.github.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Remix Theme
LUCI_DEPENDS:=+luci-base
PKG_VERSION:=0.1.0
PKG_RELEASE:=0.1
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
