#
# Copyright 2019-2020 ZHANG Zhao <Zhao.Zhang2@etu.univ-grenoble-alpes.fr>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Dashboard Pages Remix
LUCI_DEPENDS:=+luci-base +libiwinfo
PKG_BUILD_DEPENDS:=iwinfo
PKG_VERSION:=20210421.03-05
PKG_RELEASE:=20210421.03-05
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

